### ISSUE TITLE
Plan of actions for version 0.4.0

### ISSUE THREAD

**Issue by pmenhart** [heyoutline/cloud_watch#18]
I'd like to propose following updates:
* Create new branch `release_0.3` for compatibility with older applications
* Drop support for Elixir 1.5 (builds are failing already).  Use `release_0.3` if 1.5 is needed
* Replace Travis CI with GitHub actions. Define matrix of Erlang + Elixir versions to test against. See PR #16
* Remove dependency on Poison.  This would bring relief to projects that are using exclusively Jason as their JSON encoder, see issues #13, #15. Also note that both aws-elixir and ExAws are switching from Poison to Jason. See PR #17
* Add support for newer versions of [aws-elixir](https://github.com/aws-beam/aws-elixir). PR #14 submitted upgrade to 0.6.0, but 0.7.0 is already out (with incompatible module names). We should support all AWS versions from 0.5.0 upward
* Permit wide range of versions of `httpoison`. We should not restrict users in their choices
*  Fix application boundary warnings for Elixir 1.11

**Comment by pmenhart** [comment]
Added PR #19 to implement this proposal.

**Comment by pmenhart** [comment]
Hi @kuiro5,
My "action plan" for v0.4.0 was implemented. Please update list of maintainers and 'links' in mix.exs.

Looking forward to the release (I am still using my fork, for reasons explained [here](https://github.com/heyoutline/cloud_watch/issues/6#issuecomment-450379369), but periodically rebasing my modifications on top of the official codebase). 
Thanks for taking over!
Peter

**Comment by kuiro5** [comment]
Hey @pmenhart, sounds great, thanks for all the work! I'll be publishing the release tonight after updating the maintainers and links.

I'm sure you've already investigated, but I'll do some research on how other libraries have decided to handle rate limiting. Might enable us to get some of your modifications into main in a future release. 👍

**Comment by kuiro5** [comment]
v0.4.0 is released to hex, I added some of the notes from the PR into the [release](https://github.com/heyoutline/cloud_watch/releases/tag/v0.4.0). Is this okay to close?

**Comment by pmenhart** [comment]
Yes, closing the ticket. Thanks for making the release!
